# Generated by Django 5.1.4 on 2025-05-02 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='generate_finalize_monthly_salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('basic_pay', models.IntegerField()),
                ('hra', models.IntegerField()),
                ('travel_allowance', models.IntegerField()),
                ('food_allowance', models.IntegerField()),
                ('special_allowance', models.IntegerField()),
                ('car_allowance', models.IntegerField()),
                ('petrol_allowance', models.IntegerField()),
                ('driver_allowance', models.IntegerField()),
                ('medical_allowance', models.IntegerField()),
                ('internet_allowance', models.IntegerField()),
                ('paper_allowance', models.IntegerField()),
                ('epf', models.IntegerField()),
                ('employer', models.IntegerField()),
                ('employee_recovery', models.IntegerField()),
                ('Taxes', models.IntegerField()),
                ('other_deduction', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='generate_monthly_areal_deduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('start_date', models.DateField()),
                ('basic_pay', models.IntegerField()),
                ('hra', models.IntegerField()),
                ('travel_allowance', models.IntegerField()),
                ('food_allowance', models.IntegerField()),
                ('special_allowance', models.IntegerField()),
                ('car_allowance', models.IntegerField()),
                ('petrol_allowance', models.IntegerField()),
                ('driver_allowance', models.IntegerField()),
                ('medical_allowance', models.IntegerField()),
                ('internet_allowance', models.IntegerField()),
                ('paper_allowance', models.IntegerField()),
                ('epf', models.IntegerField()),
                ('employer', models.IntegerField()),
                ('employee_recovery', models.IntegerField()),
                ('other_deduction', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='generate_monthly_salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('basic_pay', models.IntegerField()),
                ('hra', models.IntegerField()),
                ('travel_allowance', models.IntegerField()),
                ('food_allowance', models.IntegerField()),
                ('special_allowance', models.IntegerField()),
                ('car_allowance', models.IntegerField()),
                ('petrol_allowance', models.IntegerField()),
                ('driver_allowance', models.IntegerField()),
                ('medical_allowance', models.IntegerField()),
                ('internet_allowance', models.IntegerField()),
                ('paper_allowance', models.IntegerField()),
                ('epf', models.IntegerField()),
                ('employer', models.IntegerField()),
                ('employee_recovery', models.IntegerField()),
                ('Taxes', models.IntegerField()),
                ('other_deduction', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Master_monthly_workday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=100)),
                ('year', models.IntegerField(null=True)),
                ('generateStatus', models.CharField(max_length=100)),
                ('updateStatus', models.CharField(max_length=100)),
                ('finalisedStatus', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Payroluser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
