# Generated by Django 5.1.4 on 2025-05-02 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payrols', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='generate_finalize_monthly_salary',
        ),
    ]
