# Generated by Django 5.1.4 on 2025-05-09 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrols', '0002_delete_generate_finalize_monthly_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerateMonthlyArealDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('basic_pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('travel_allowance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('food_allowance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('special_allowance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('car_allowance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('petrol_allowance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('driver_allowance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('medical_allowance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('internet_allowance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paper_allowance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('epf', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employer', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employee_recovery', models.DecimalField(decimal_places=2, max_digits=10)),
                ('other_deduction', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.DeleteModel(
            name='generate_monthly_areal_deduction',
        ),
    ]
