# Generated by Django 5.1.4 on 2025-05-09 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrols', '0003_generatemonthlyarealdeduction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='generate_monthly_areal_deduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('start_date', models.DateField()),
                ('basic_pay', models.IntegerField()),
                ('hra', models.IntegerField()),
                ('travel_allowance', models.IntegerField()),
                ('food_allowance', models.IntegerField()),
                ('special_allowance', models.IntegerField()),
                ('car_allowance', models.IntegerField()),
                ('petrol_allowance', models.IntegerField()),
                ('driver_allowance', models.IntegerField()),
                ('medical_allowance', models.IntegerField()),
                ('internet_allowance', models.IntegerField()),
                ('paper_allowance', models.IntegerField()),
                ('epf', models.IntegerField()),
                ('employer', models.IntegerField()),
                ('employee_recovery', models.IntegerField()),
                ('other_deduction', models.IntegerField()),
                ('taxes', models.IntegerField()),
                ('remark', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='GenerateMonthlyArealDeduction',
        ),
    ]
