# Generated by Django 5.1.4 on 2025-05-09 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrols', '0004_generate_monthly_areal_deduction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generate_monthly_areal_deduction',
            name='remark',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
