# Generated by Django 5.1.4 on 2025-05-09 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrols', '0005_alter_generate_monthly_areal_deduction_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='generate_monthly_areal_deduction',
            name='total',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
