# Generated by Django 5.1.4 on 2025-05-09 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrols', '0006_generate_monthly_areal_deduction_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generate_monthly_areal_deduction',
            name='total',
            field=models.FloatField(),
        ),
    ]
