# Generated by Django 5.1.4 on 2025-05-13 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrols', '0007_alter_generate_monthly_areal_deduction_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_workday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('total_days', models.IntegerField()),
                ('leave', models.IntegerField()),
                ('weekends', models.IntegerField()),
                ('parity_off', models.IntegerField()),
                ('leave_without_pay', models.IntegerField()),
            ],
        ),
    ]
