# Generated by Django 5.1.4 on 2025-05-13 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrols', '0008_add_workday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_workday',
            name='month',
            field=models.CharField(max_length=7),
        ),
    ]
