# Generated by Django 5.1.4 on 2025-05-13 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrols', '0009_alter_add_workday_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_workday',
            name='workdays',
            field=models.FloatField(default=20),
            preserve_default=False,
        ),
    ]
