# Generated by Django 5.1.4 on 2025-06-11 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payrols', '0011_add_workday_employee_id_add_workday_employee_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='add_workday',
        ),
        migrations.DeleteModel(
            name='generate_monthly_areal_deduction',
        ),
    ]
