# Generated by Django 5.1.4 on 2025-06-02 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='add_workday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=7, unique=True)),
                ('total_days', models.IntegerField()),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('employee_name', models.CharField(max_length=50, unique=True)),
                ('leave', models.IntegerField()),
                ('weekends', models.IntegerField()),
                ('parity_off', models.IntegerField()),
                ('leave_without_pay', models.IntegerField()),
                ('workdays', models.FloatField()),
                ('payable_days', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='generate_monthly_areal_deduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('start_date', models.DateField()),
                ('basic_pay', models.IntegerField()),
                ('hra', models.IntegerField()),
                ('travel_allowance', models.IntegerField()),
                ('food_allowance', models.IntegerField()),
                ('special_allowance', models.IntegerField()),
                ('car_allowance', models.IntegerField()),
                ('petrol_allowance', models.IntegerField()),
                ('driver_allowance', models.IntegerField()),
                ('medical_allowance', models.IntegerField()),
                ('internet_allowance', models.IntegerField()),
                ('paper_allowance', models.IntegerField()),
                ('epf', models.IntegerField()),
                ('employer', models.IntegerField()),
                ('employee_recovery', models.IntegerField()),
                ('other_deduction', models.IntegerField()),
                ('taxes', models.IntegerField()),
                ('remark', models.CharField(blank=True, max_length=50, null=True)),
                ('total', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='new_employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('wife_name', models.CharField(max_length=100)),
                ('current_address', models.CharField(max_length=100)),
                ('permanent_address', models.CharField(max_length=100)),
                ('no_of_kids', models.IntegerField()),
                ('date_of_birth', models.DateField()),
                ('date_of_joining', models.DateField()),
                ('marriage_anniversary_date', models.DateField()),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='salary_add',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('start_date', models.DateField()),
                ('basic_pay', models.IntegerField()),
                ('hra', models.IntegerField()),
                ('travel_allowance', models.IntegerField()),
                ('food_allowance', models.IntegerField()),
                ('special_allowance', models.IntegerField()),
                ('car_allowance', models.IntegerField()),
                ('petrol_allowance', models.IntegerField()),
                ('driver_allowance', models.IntegerField()),
                ('medical_allowance', models.IntegerField()),
                ('internet_allowance', models.IntegerField()),
                ('paper_allowance', models.IntegerField()),
                ('epf', models.IntegerField()),
                ('employer', models.IntegerField()),
                ('employee_recovery', models.IntegerField()),
                ('other_deduction', models.IntegerField()),
                ('total', models.FloatField()),
            ],
        ),
    ]
