# Generated by Django 5.1.4 on 2025-06-11 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='generate_monthly_salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50)),
                ('month', models.CharField(max_length=7)),
                ('basic_pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('travel_allowance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('food_allowance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('special_allowance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('car_allowance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('petrol_allowance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('driver_allowance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('medical_allowance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('internet_allowance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paper_allowance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('epf', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employer', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employee_recovery', models.DecimalField(decimal_places=2, max_digits=10)),
                ('other_deduction', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
