# Generated by Django 5.1.4 on 2025-06-17 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0002_generate_monthly_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_workday',
            name='month',
            field=models.CharField(max_length=7),
        ),
    ]
