# Generated by Django 5.1.4 on 2025-06-25 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0003_alter_add_workday_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_employee',
            name='bank_account_no',
            field=models.CharField(default=712410110007785, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='new_employee',
            name='bank_name',
            field=models.CharField(default=98765432123, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='new_employee',
            name='epf_no',
            field=models.CharField(default=987654321, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='new_employee',
            name='ifsc_code',
            field=models.CharField(default=987654321, max_length=50),
            preserve_default=False,
        ),
    ]
