# Generated by Django 5.1.4 on 2024-12-23 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_employee',
            name='department',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='new_employee',
            name='location',
            field=models.CharField(default=13, max_length=50),
            preserve_default=False,
        ),
    ]
