# Generated by Django 5.1.4 on 2025-01-04 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrs', '0002_new_employee_department_new_employee_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='salary_add',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('start_date', models.DateField()),
                ('basic_pay', models.IntegerField()),
                ('hra', models.IntegerField()),
                ('travel_allowance', models.IntegerField()),
                ('food_allowance', models.IntegerField()),
                ('special_allowance', models.IntegerField()),
                ('car_allowance', models.IntegerField()),
                ('petrol_allowance', models.IntegerField()),
                ('driver_allowance', models.IntegerField()),
                ('medical_allowance', models.IntegerField()),
                ('internet_allowance', models.IntegerField()),
                ('paper_allowance', models.IntegerField()),
                ('epf', models.IntegerField()),
                ('employer', models.IntegerField()),
                ('employee_recovery', models.IntegerField()),
                ('other_deduction', models.IntegerField()),
            ],
        ),
    ]
