# Generated by Django 5.1.4 on 2025-05-09 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrs', '0003_salary_add'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary_add',
            name='total',
            field=models.FloatField(default=20),
            preserve_default=False,
        ),
    ]
