# Generated by Django 5.1.4 on 2025-06-25 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrs', '0004_salary_add_total'),
    ]

    operations = [
        migrations.DeleteModel(
            name='new_employee',
        ),
        migrations.DeleteModel(
            name='salary_add',
        ),
    ]
